branch-defaults:
  master:
    environment: flask-rest-author-manager-app-dev
    group_suffix: null
global:
  application_name: flask-rest-author-manager-app
  branch: null
  default_ec2_keyname: keypair-ohio
  default_platform: Python 3.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
